In [85]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
df=pd.read_csv("general_data.csv") 
df.head(2)

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeID,Gender,...,NumCompaniesWorked,Over18,PercentSalaryHike,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager
0,51,No,Travel_Rarely,Sales,6,2,Life Sciences,1,1,Female,...,1.0,Y,11,8,0,1.0,6,1,0,0
1,31,Yes,Travel_Frequently,Research & Development,10,1,Life Sciences,1,2,Female,...,0.0,Y,23,8,1,6.0,3,5,1,4

In [86]:
df["NumCompaniesWorked"].fillna(df['NumCompaniesWorked'].mean(),inplace=True)
df["TotalWorkingYears"].fillna(df['TotalWorkingYears'].mean(),inplace=True)
df.drop(['EmployeeID', 'EmployeeCount','Over18','StandardHours'],axis=1,inplace=True)

In [87]:
df['Attrition'].replace({'No': 0, 'Yes': 1},inplace = True)
df['Gender'].replace({'Female': 0, 'Male': 1},inplace = True)
df['Department'].replace({'Sales': 0, 'Research & Development': 1, 'Human Resources' : 2},inplace = True)
df['EducationField'].replace({'Life Sciences': 0, 'Other': 1, 'Marketing' : 2, 'Medical':3, 'Technical Degree':4, 'Human Resources' : 5 },inplace = True)
df['BusinessTravel'].replace({'Travel_Rarely': 3, 'Travel_Frequently': 2,'Non-Travel': 1},inplace = True)

In [88]:
df.head(4)

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,Gender,JobLevel,JobRole,MaritalStatus,MonthlyIncome,NumCompaniesWorked,PercentSalaryHike,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager
0,51,0,3,0,6,2,0,0,1,Healthcare Representative,Married,131160,1.0,11,0,1.0,6,1,0,0
1,31,1,2,1,10,1,0,0,1,Research Scientist,Single,41890,0.0,23,1,6.0,3,5,1,4
2,32,0,2,1,17,4,1,1,4,Sales Executive,Married,193280,1.0,15,3,5.0,2,5,0,3
3,38,0,1,1,2,5,0,1,3,Human Resources,Married,83210,3.0,11,3,13.0,5,8,7,5

In [89]:
from scipy.stats import pearsonr

In [90]:
stats,p=pearsonr(df.Attrition,df.BusinessTravel)
print(stats,p)

7.377694602222606e-05 0.9960919945440154

In [91]:
stats,p=pearsonr(df.Attrition,df.Department)
print(stats,p)

0.04820581991833704 0.0013638319632114106

In [92]:
stats,p=pearsonr(df.Attrition,df.DistanceFromHome)
print(stats,p)

-0.009730141010179438 0.5182860428049617

In [93]:
st,q=pearsonr(df.Attrition,df.EducationField)
print(st,q)

0.0049707002330168955 0.7413985395371094

In [94]:
st3,g=pearsonr(df.Attrition,df.Education)
st4,m=pearsonr(df.Attrition,df.EducationField)
st5,n=pearsonr(df.Attrition,df.Gender)
st6,s=pearsonr(df.Attrition,df.NumCompaniesWorked)
st7,l=pearsonr(df.Attrition,df.PercentSalaryHike)
st8,gg=pearsonr(df.Attrition,df.TotalWorkingYears)
st9,mm=pearsonr(df.Attrition,df.TrainingTimesLastYear)
st10,nn=pearsonr(df.Attrition,df.YearsAtCompany)
st11,ss=pearsonr(df.Attrition,df.YearsSinceLastPromotion)
st12,ll=pearsonr(df.Attrition,df.YearsWithCurrManager)

In [95]:
print(st3,g)
print(st4,m)
print(st5,n)
print(st6,s)
print(st7,l)
print(st3,gg)
print(st8,mm)
print(st9,nn)
print(st10,ss)
print(st11,ll)

-0.015111167710968737 0.3157293177118575
0.0049707002330168955 0.7413985395371094
0.01812507887701033 0.22881970951790567
0.04223152661444658 0.005032276452667087
0.032532594891052195 0.030743386433369824
-0.015111167710968737 5.473147954406791e-30
-0.17011136633026647 0.001024706191536548
-0.049430576244253066 3.163883122493571e-19
-0.13439221398997386 0.02833033618939086
-0.03301877514258329 1.7339322652951965e-25

In [96]:
df.corr()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,Gender,JobLevel,MonthlyIncome,NumCompaniesWorked,PercentSalaryHike,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager
Age,1.000000,-0.159205,0.024751,0.010846,0.006963,-0.035706,9.022624e-03,-3.935163e-02,-0.002884,-0.044314,0.298528,-0.033137,-0.031753,0.680419,-0.027308,0.311309,0.216513,0.202089
Attrition,-0.159205,1.000000,0.000074,0.048206,-0.009730,-0.015111,4.970700e-03,1.812508e-02,-0.010290,-0.031176,0.042232,0.032533,-0.006839,-0.170111,-0.049431,-0.134392,-0.033019,-0.156199
BusinessTravel,0.024751,0.000074,1.000000,0.010982,0.024616,0.002755,1.613692e-02,-3.924316e-02,0.046111,-0.037597,0.022365,-0.031054,0.003683,0.033960,-0.041888,-0.014575,-0.032591,-0.022636
Department,0.010846,0.048206,0.010982,1.000000,-0.012134,0.004597,8.230789e-02,-3.158225e-03,-0.002923,0.032237,0.003945,0.007840,-0.010512,0.019814,-0.012866,-0.010078,-0.014845,-0.018016
DistanceFromHome,0.006963,-0.009730,0.024616,-0.012134,1.000000,-0.008638,-2.561585e-03,-4.417279e-02,-0.037329,-0.021607,-0.013818,0.038125,0.011169,0.009361,-0.009001,0.031684,0.002290,0.021584
Education,-0.035706,-0.015111,0.002755,0.004597,-0.008638,1.000000,-2.053274e-02,-1.654683e-02,0.045746,0.006410,-0.016219,-0.040531,0.001261,-0.010712,0.010472,0.006080,0.022490,0.005358
EducationField,0.009023,0.004971,0.016137,0.082308,-0.002562,-0.020533,1.000000e+00,-4.490947e-17,-0.010236,-0.000373,-0.013130,-0.020416,0.035322,0.002500,-0.026151,-0.009610,0.032887,-0.014331
Gender,-0.039352,0.018125,-0.039243,-0.003158,-0.044173,-0.016547,-4.490947e-17,1.000000e+00,-0.026854,0.007530,-0.066796,0.011841,0.019237,-0.027571,-0.030167,-0.017277,-0.021812,0.004438
JobLevel,-0.002884,-0.010290,0.046111,-0.002923,-0.037329,0.045746,-1.023552e-02,-2.685434e-02,1.000000,0.047316,-0.009844,0.010973,0.000993,-0.036934,-0.032500,-0.064219,-0.060811,-0.055251
MonthlyIncome,-0.044314,-0.031176,-0.037597,0.032237,-0.021607,0.006410,-3.729684e-04,7.530386e-03,0.047316,1.000000,-0.020710,0.004325,0.026930,-0.033758,0.050112,0.000995,0.065219,0.024304
NumCompaniesWorked,0.298528,0.042232,0.022365,0.003945,-0.013818,-0.016219,-1.313024e-02,-6.679585e-02,-0.009844,-0.020710,1.000000,0.030825,0.017130,0.238052,-0.032239,-0.117820,-0.036618,-0.109480
PercentSalaryHike,-0.033137,0.032533,-0.031054,0.007840,0.038125,-0.040531,-2.041629e-02,1.184147e-02,0.010973,0.004325,0.030825,1.000000,0.012548,-0.018717,-0.037392,-0.029707,-0.029542,-0.040864
StockOptionLevel,-0.031753,-0.006839,0.003683,-0.010512,0.011169,0.001261,3.532247e-02,1.923659e-02,0.000993,0.026930,0.017130,0.012548,1.000000,0.002693,-0.069902,0.007886,0.019063,0.017757
TotalWorkingYears,0.680419,-0.170111,0.033960,0.019814,0.009361,-0.010712,2.500492e-03,-2.757123e-02,-0.036934,-0.033758,0.238052,-0.018717,0.002693,1.000000,-0.040705,0.626876,0.403995,0.458425
TrainingTimesLastYear,-0.027308,-0.049431,-0.041888,-0.012866,-0.009001,0.010472,-2.615119e-02,-3.016746e-02,-0.032500,0.050112,-0.032239,-0.037392,-0.069902,-0.040705,1.000000,-0.007894,0.016121,-0.013270
YearsAtCompany,0.311309,-0.134392,-0.014575,-0.010078,0.031684,0.006080,-9.610341e-03,-1.727689e-02,-0.064219,0.000995,-0.117820,-0.029707,0.007886,0.626876,-0.007894,1.000000,0.618409,0.769212
YearsSinceLastPromotion,0.216513,-0.033019,-0.032591,-0.014845,0.002290,0.022490,3.288669e-02,-2.181181e-02,-0.060811,0.065219,-0.036618,-0.029542,0.019063,0.403995,0.016121,0.618409,1.000000,0.510224
YearsWithCurrManager,0.202089,-0.156199,-0.022636,-0.018016,0.021584,0.005358,-1.433109e-02,4.438010e-03,-0.055251,0.024304,-0.109480,-0.040864,0.017757,0.458425,-0.013270,0.769212,0.510224,1.000000